### ISSUE TITLE
Create glossary for contributors

### ISSUE THREAD

**Issue by MaxymVlasov** [kubernetes-i18n-ukrainian/website#101]
Потрібно розробити базовий словник термінів для перекладу.

І туди ж написати про стиль перекладу з 
```
<---
Orig text
-->
Переклад
```

[Приклад як це виглядає у корейців](https://kubernetes.io/ko/docs/contribute/localization_ko/#%EC%9A%A9%EC%96%B4%EC%A7%91)

**Comment by butuzov** [comment]
Щодо коментування оригіналу

1) у VSC гарно працюємо з хоткеями (відкрийте keyboard shortcuts).
    * `Copy Line Down` (Насправді весь selection, а не тільки лінію)
    * `Toggle Line Comment` (теж весь селекшен а не тільки лінію) + потрібно буде відбити початок та кінець комендування новими лініями.

Це треба походу в першу чергу (насобачитись), бо я вже кілька разів повертався та змінював що не написав відпочатку.
    
2) Встановіть cSpell extension https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker-ukrainian

**Comment by MaxymVlasov** [comment]
Не зрозумів про `Copy Line Down`. Його [тут просто нема](https://code.visualstudio.com/shortcuts/keyboard-shortcuts-linux.pdf)

А замість `Toggle Line Comment` краще використати `Toggle block comment` (`Ctrl + Shift + A`) - тоді не треба буде нічого відбивати.

П.Н. Дуже крутий екстеншн, дякую

**Comment by butuzov** [comment]
1. Ти його можеш знайти в списку шорткатів (щоправда там мабуть краще замість вних використовувати вверх). cmd+K cmd+S (ctrl+K ctrl+S)
2. Ця штука працбє ще гірше, ніж просто комент/анкомент ліній. ну принамйні в мене.

---
фігове відео демка

![t](https://user-images.githubusercontent.com/651824/74006620-e1bd1f00-4984-11ea-9bbf-0f784eb2f037.gif)
