### ISSUE TITLE
Localize '/docs/concepts/overview/what-is-kubernetes' path

### ISSUE THREAD

**Issue by MaxymVlasov** [kubernetes-i18n-ukrainian/website#12]
* Location popularity: 9/100
* Site path: https://kubernetes.io/docs/concepts/overview/what-is-kubernetes
* Git EN dir path: https://github.com/kubernetes-i18n-ukrainian/website/tree/master/content/en/docs/concepts/overview
* Copy file(s) to UK: `mkdir -p content/uk/docs/concepts/overview && cp content/en/docs/concepts/overview/what-is-kubernetes.md content/en/docs/concepts/overview/_index.md content/uk/docs/concepts/overview`

**Comment by butuzov** [comment]
assigned to me as part of the #100

**Comment by MaxymVlasov** [comment]
@butuzov, розберіться, будь ласка, з @anastyakulyk хто з вас його перекладатиме, бо воно є в #1, але переклад наче ще не почався

**Comment by butuzov** [comment]
Я вже почав, бо без цього тупо не збирається.

**Comment by anastyakulyk** [comment]
Зрозуміла, я тоді цю статтю не чіпаю

**Comment by butuzov** [comment]
#102
